const tourEditSchema = z.object({
  name: z.string().min(3, { message: "Name must be at least 3 characters" }),
  description: z.string().min(20, { message: "Description should be at least 20 characters" }),
  destinationId: z.coerce.number().positive({ message: "Please select a destination" }),
  tripType: z.string().min(1, { message: "Please select a trip type" }),
  duration: z.coerce.number().min(1, { message: "Duration is required" }),
  durationType: z.enum(["days", "hours"], { message: "Please select duration type" }),
  startDate: z.date({ required_error: "Start date is required" }),
  endDate: z.date({ required_error: "End date is required" }),
  numPassengers: z.coerce.number().min(1, { message: "At least 1 passenger is required" }),
  price: z.coerce.number().min(0, { message: "Price must be a positive number" }),
  discountedPrice: z.coerce.number().min(0, { message: "Discounted price must be a positive number" }).optional().nullable(),
  included: z.array(z.string()).default([]),
  excluded: z.array(z.string()).default([]),
  itinerary: z.string().min(20, { message: "Itinerary should provide sufficient details" }),
  maxGroupSize: z.coerce.number().min(1, { message: "Group size must be at least 1" }).optional().nullable(),
  featured: z.boolean().default(false),
  status: z.string().default("active"),
  // Added missing fields from schema
  imageUrl: z.string().optional(),
  galleryUrls: z.array(z.string()).optional(),
  currency: z.string().default("EGP"),
  rating: z.coerce.number().min(0).max(5).optional().nullable(),
  reviewCount: z.coerce.number().min(0).optional().nullable(),
  categoryId: z.coerce.number().positive().optional().nullable(),
  // Arabic fields
  nameAr: z.string().optional(),
  descriptionAr: z.string().optional(),
  itineraryAr: z.string().optional(),
  includedAr: z.array(z.string()).optional(),
  excludedAr: z.array(z.string()).optional(),
  hasArabicVersion: z.boolean().default(false),
});

const form = useForm<TourFormValues>({
  resolver: zodResolver(tourEditSchema),
  defaultValues: {
    name: tour?.name || "",
    description: tour?.description || "",
    destinationId: tour?.destinationId || 0,
    tripType: tour?.tripType || "",
    duration: tour?.duration || 1,
    durationType: tour?.durationType || "days",
    startDate: tour?.startDate ? new Date(tour.startDate) : new Date(),
    endDate: tour?.endDate ? new Date(tour.endDate) : new Date(new Date().setDate(new Date().getDate() + 1)),
    numPassengers: tour?.numPassengers || 1,
    price: tour?.price ? (tour.price / 100) : 0, // Convert from cents to EGP
    discountedPrice: tour?.discountedPrice ? (tour.discountedPrice / 100) : null, // Convert from cents to EGP
    included: tour?.included || [],
    excluded: tour?.excluded || [],
    itinerary: tour?.itinerary || "",
    maxGroupSize: tour?.maxGroupSize || 10,
    featured: tour?.featured || false,
    status: tour?.status || "active",
    // Added missing fields
    imageUrl: tour?.imageUrl || "",
    galleryUrls: tour?.galleryUrls || [],
    currency: tour?.currency || "EGP",
    rating: tour?.rating || null,
    reviewCount: tour?.reviewCount || 0,
    categoryId: tour?.categoryId || null,
    // Arabic fields
    nameAr: tour?.nameAr || "",
    descriptionAr: tour?.descriptionAr || "",
    itineraryAr: tour?.itineraryAr || "",
    includedAr: tour?.includedAr || [],
    excludedAr: tour?.excludedAr || [],
    hasArabicVersion: tour?.hasArabicVersion || false,
  },
}); 